### ISSUE TITLE
HUD reticle target registration incorrectly offset.

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/Invader#10]
It seems the target point is incorrect, being lower than it should.
http://vaporeon.io/hosted/halo/misc/anhalo.png

https://cdn.discordapp.com/attachments/424172560272588807/503101634843246592/20181020_150313.mp4

**Comment by Vaporeon** [comment]
This also effects controller auto aim.

**Comment by Vaporeon** [comment]
This seems to not be a thing now for some reason.

**Comment by Kavawuvi** [comment]
I "fixed" the issue by hardcoding a value to 12, but this broke anything that doesn't have the model node, "bip01 head", at index 12 (such as elites which have it at index 17). But I actually fixed the issue in https://github.com/Kavawuvi/Invader/commit/a448d9c403ea044b3cdeccf4dfef27e735225ab8
