### ISSUE TITLE
Create a new tool that simply opens and re-saves tags (invader-touch?)

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/invader#104]
This could be quite useful as it would allow and easy way to strip hidden vales from tags that should not be there and also allow clearing useless pointers that guerilla.exe leaves in too. It would also reset the tag CRC that could be wrong in an otherwise good tag.

It was suggested that invader-edit could be used to do this but I don't think it would be too bad to have this as its own tool.

**Comment by Vaporeon** [comment]
I'd like to add, it may be considered that having a tool set the tag CRC32 defeats the purpose of checking that value in the first place but I do not consider this to be the case.

The point of the CRC32 in the blam header is to verify the tag data is the same as it was since it was saved by the tool that created or edited it. It is not there to verify if the tag data is what you expect it to be or even that the tag data is sane. Since a tag that is saved by invader should always be valid tag data then it makes sense to give it a valid CRC32. If someone were to run this tool on a set of tags with invalid CRC's without first checking if the tag data is what they expected then they would be idiots.

**Comment by Kavawuvi** [comment]
Added it in release [0.23.0](https://github.com/Kavawuvi/invader/releases/tag/0.23.0). The tool is called invader-strip.
