### ISSUE TITLE
[invader-strip] add --process-tags argument to enable previous behaviour of invader-strip.

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/invader#108]
When used the tags get pre-processed like they did before. It might be useful, especially since invader-compare does not exist yet. I did not think to suggest this when changing that was being discussed.

**Comment by Kavawuvi** [comment]
Done https://github.com/Kavawuvi/invader/commit/bf675af7de1499a08408fae6c4192438b71aa765
