### ISSUE TITLE
Some custom weapon tags function incorrectly

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/Invader#11]
Testing some random tags I found that these H2 ones have some issues. The shotgun will not fire all of its rounds. There might be something off with the carbine effect too.

Using these tags, build levels/test/bloodgulch/bloodgulch_test
http://vaporeon.io/hosted/halo/misc/h2_tag_test.7z

**Comment by Kavawuvi** [comment]
Fixed the shotgun issue in https://github.com/Kavawuvi/Invader/commit/1570c0ff553cdb5a32503452d1c1f0b5f6d6b01e

I don't notice anything wrong with the Carbine, either.
