### ISSUE TITLE
[invader] Implement some unused tag classes for completeness

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/invader#110]
There are some unused tag classes that the HEK still supports.
These should possibly be implemented, while not a priority the HEK can still process these tags in some way. the classes include:

`continuous_damage_effect`
`multiplayer_scenario_description`
`preferences_network_game`
`spheroid`

**Comment by Kavawuvi** [comment]
I suppose a way this can be tested is by using tag collection tags. There might be some hidden stuff though.

Feb 5, 2020, 07:17 by notifications@github.com:

**Comment by Kavawuvi** [comment]
I suppose a way this can be tested is by using tag collection tags. There might be some hidden stuff though.

**Comment by Kavawuvi** [comment]
Done as of 2e505af69427e780a68dfa83e814109c25b7490c though if there's any hidden stuff, that will be hard to test/find since it's unused
