### ISSUE TITLE
[New feature] Create a tool to generate tag collection tags

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/invader#111]
It would be useful to have tool that takes a list of tags as input and creates a tag collection tag from this.

**Comment by Vaporeon** [comment]
perhaps it could work from the data directory the same way string lists do. this way existing tag collections could be converted to these text input files too.

**Comment by Kavawuvi** [comment]
This should use invader-indexer type files (when used on a cache file).

**Comment by Vaporeon** [comment]
This was done in 9cd04421aa70f19f0e9a2f478b000bacebc4b522
