### ISSUE TITLE
[invader] Create tag decorruption tool.

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/invader#115]
Originally it was intended that invader should not be in the businesses of fixing broken tags for you other than fixing purposefully corrupted maps with the intention of recovering tags from them. The reason for this being it should not be the job of an editing kit to fix bugs from other 3rd party editing tools like HEK+.

However upon the discovery that stock maps themselves contain equally broken tags including those in the base HEK I think this stance should be changed.

Having a tool that can ease the process of fixing common issues would be very useful when dealing with this game. Thanks to gearbox not catching this you can't even build a simple stock based map with invader without at least fixing one such invalid tag manually. (as should be the case, these tags are broken)

**Comment by Kavawuvi** [comment]
Done. invader-bludgeon fulfills this role.
