### ISSUE TITLE
[invader-bludgeon] Add an option for changing model references to gbxmodel

### ISSUE THREAD

**Issue by Kavawuvi** [Kavawuvi/invader#116]
Nothing uses .model anymore, and there are dozens of tags that have .model references that get changed to .gbxmodel on load anyway.

Also, for the sake of tag comparison, invader-strip should be doing this, anyway.

**Comment by Kavawuvi** [comment]
We should only do this for loose tags as well as on extraction of Xbox maps, but if and when we build Xbox maps (#138) then .gbxmodel tags should be converted to .model tags.

**Comment by Kavawuvi** [comment]
invader-bludgeon should do this. Having it be part of the parser is bullshit.

**Comment by Vaporeon** [comment]
Since we support real model tags now we likely do not want to do this.

I am aware that the tags released with the HEK will not compile, but that is what happens when you do horrible things like patching the map compiler to change tag classes at map build time. We still have `invader-refactor`.
