### ISSUE TITLE
[invader] Implement special handling of Xbox "multipurpose" bitmaps.

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/invader#117]
Since we extract Xbox tags now we may want to do some things so ease the usage of such data.

First I think we should add some flags to the bitmap tag class to denote that the bitmap uses the Xbox multipurpose color channel order (one in usage flags and one in the bitmap data flags).

The advantages to this are:
 - We can now error if such a tag is used in a cache file for an engine that does not support the correct channel order e.g. Custom Edition.
 - Anything in invader that may want to display this bitmap can do so correctly.

`invader-extract` can set these flags on extraction of Xbox maps if the bitmap is referenced as a "multipurpose" and invader-bitmap can be given the option to swap the channels on tag creation, if we want to support that for any reason. Raw color plate data should always be in the "PC" format to match all the raw data currently in use though.

**Comment by Kavawuvi** [comment]
Nope
