### ISSUE TITLE
[invader-build] Don't include raw data in MCC maps

### ISSUE THREAD

**Issue by Kavawuvi** [Kavawuvi/invader#123]
This stuff isn't used at this point in time, nor do we know if it'll be used in this exact way if it is even used.

**Comment by Vaporeon** [comment]
Perhaps `-n` should do what it does now so we have some way to make maps with raw data for testing ways to get MCC to load it one way or another.

This can be changed when raw data loading MCC is finalised.

**Comment by Kavawuvi** [comment]
The original request was done, but we should figure out -n later

**Comment by Kavawuvi** [comment]
After a few weeks of consideration, implementing `-n` for MCC maps really isn't worth implementing.

In honesty, this issue was made before we realized CEA would be released in the way it was, and it really isn't worth it keeping raw data in the map under the hopes that some mod or update will "enable" it.
