### ISSUE TITLE
Wrong path separators used in cache tag paths if map is compiled on Linux

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/Invader#13]
If you build maps on Linux and use forward slashes to point to the scenario in the invader command argument, the forward slashes will be used in the compiled maps tag paths.
Building using escaped back slashes works as intended.

**Comment by Kavawuvi** [comment]
Fixed in https://github.com/Kavawuvi/Invader/commit/d939c855f5c1d021b543fbec6767658ea23ced21
