### ISSUE TITLE
[invader] Clear cache only or undefined flags when parsing loose tags.

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/invader#139]
We should clear any undefined flags or flags that are only applicable when cached since normal HEK tags will not have these.

**Comment by Vaporeon** [comment]
Not clearing these can cause tags to be mismatched by `invader-compare` e.g. bitmap tags and the "make it actually work" flag will cause extracted tags to mismatch the originals used to build a map.

**Comment by Kavawuvi** [comment]
Done in cccf1ccc
