### ISSUE TITLE
[invader-refactor] Allow the use of multiple edit commands in one invocation

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/invader#140]
We should change `invader-refactor` to work with multiple commands at once like `sed` does with -e.

This should be done for performance reasons as changing a large amount of references like for example re-referencing shader tags to matching shaders of another class can take a very long time.

**Comment by Kavawuvi** [comment]
Done as of https://github.com/Kavawuvi/invader/commit/6710c43bca61e7f47326230d2538c72d3b844c3b
