### ISSUE TITLE
[invader-build] support child scenarios in scenario tags.

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/invader#141]
Currently child scenarios are not supported. When tool.exe builds a map it will merge the content of referenced child scenarios into the main scenario tag and if there are scripts it will merge the source data and recompile them.

Therefore proper support of this depends on #80 and ALL scenario tags must have script source data intact (generated or otherwise).

Tool built cache files will have invalid references for child scenarios however since the content was merged by that point the cache reference should continue to be ignored.

**Comment by Kavawuvi** [comment]
Done as of https://github.com/Kavawuvi/invader/commit/1cf487953f682d7999d6b9cae51cdb9b76fd2919
