### ISSUE TITLE
[invader-build] AI pathfinding seems broken around scenery objects

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/invader#143]
This was noticeable in "c40"

A jackal outside the main control room entrance walks in place into a covenant crate.
Some grunts also walk in-place into the same object further down the main pathway.

**Comment by Kavawuvi** [comment]
Fixed as of https://github.com/Kavawuvi/invader/commit/46b75b789ad2507bcb51ad9f0209677b8f2899d5
