### ISSUE TITLE
[invader-resource] Custom resource maps do not work

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/invader#146]
This option seems to have been broken at some point. Tested this when making a Custom Edition 32-bit texture bitmaps.map for use with tag extraction.

**Comment by Vaporeon** [comment]
On closer inspection it might be the generated resource map itself having incorrect tag paths.

**Comment by Vaporeon** [comment]
Building a stock map with a bitmaps.map made from stock tags will cause invader-build to segfault.

**Comment by Vaporeon** [comment]
`invader-build` has been fixed in 086d5a64964ce2c9cf1488288221e05a3596fbb0

**Comment by Kavawuvi** [comment]
Fixed in https://github.com/Kavawuvi/invader/commit/b467a663f69fd6df89200d5d8e494204c438e240
