### ISSUE TITLE
[invader-resource] Add support for the --with-index option

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/invader#147]
Since using this tool to make resource maps for distribution to Custom Edition users is not really a valid use case any more, I don't think we should care what gets made with it.

Adding this option would make this tool a feature complete implementation of whatever gearbox used to make the resource maps for their versions of Halo. Then should anyone need to do this for any reason, the tool for it is there.

**Comment by Kavawuvi** [comment]
Done as of https://github.com/Kavawuvi/invader/commit/017e90d4291a6da474bdf9f13068e10dbe1f452c
