### ISSUE TITLE
[invader] MCC Loads retail format maps compressed with CEA compression.

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/invader#150]
This completely breaks how we handle MCC maps, so we have to look into this.

**Comment by Vaporeon** [comment]
So it seems MCC maps are an extension of Retail maps rather than simply a change to the format

The changes are:
- base memory address can be arbitrary, the game determines it on map load
- BSP vertices can optionally be stored separately, but the original method still works.

Since the game determines this based on the map itself, we should be able to too instead of relying on the engine version+compression, which is now unreliable.

**Comment by Vaporeon** [comment]
Perhaps we should have invader treat decompressed MCC maps the same way as retail, including keeping the engine version of 7. The map parser should then calculate the base memory address of all cache files it loads and be able to parse the CEA specific BSP vertices if they are present.

**Comment by Kavawuvi** [comment]
Fixed everything as of https://github.com/Kavawuvi/invader/commit/85279a575bc9e61605e09d021858f4ff4beede04
