### ISSUE TITLE
[invader-compare] only show plain paths with -s

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/invader#159]
This would make it nicer to pipe into something. Currently it shows the matched/mismatched prefix still.

**Comment by Vaporeon** [comment]
Maybe this could be an argument to return plain paths.
If you don't use -s, then you would get plain paths for all common tags.

**Comment by Kavawuvi** [comment]
Done as of 9b8f5eedc19d31fe9ee9a31626e15a7a190d9b0e
