### ISSUE TITLE
[invader-build] c10 distress signal does not play near downed pelican.

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/invader#160]
There is meant to be a repeating radio transmission at the start of this level, however it does not work if the map was built with invader. Tested using freshly extracted tags from using invader-extract on the original retail maps.

tool.exe maps built with the same tags on the other hand work as intended.

**Comment by Kavawuvi** [comment]
This sounds like it could be an issue with conversations. s3anyboy reported an issue, earlier, regarding some conversations also not working correctly on MCC.

**Comment by Vaporeon** [comment]
It is interesting to note that the dialog sound tag for this in contained in the HEK, meaning the map that had this issue used a tag that had not been previously extracted.

**Comment by Kavawuvi** [comment]
Fixed as of 8c3785e53351f80d3fdde68d651fa71d6f1ae1b0
