### ISSUE TITLE
[invader-build] detail_object_collection tags fail to render in invader maps under some circumstances

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/invader#163]
An example a30.map that works when built with with tool.exe is [here](https://cdn.discordapp.com/attachments/375392801539620876/711349596307324928/a30-fucked.tar.xz)

**Comment by Kavawuvi** [comment]
Fixed as of https://github.com/Kavawuvi/invader/commit/1cbacdff724d55edc6219b36cb05e63d62327197
