### ISSUE TITLE
[invader-extract] Error if a map contains invalid tag path strings.

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/invader#167]
We should error to prevent writing or attempting to write bogus tag paths to disk.
This will mean protected AKA corrupt maps will need to be sanitised before anything can be extracted, but this should be a requirement anyway.

**Comment by Kavawuvi** [comment]
Fixed as of  https://github.com/Kavawuvi/invader/commit/9ec97f288100567cdbf0acf4ae47cff04ebeb68b
