### ISSUE TITLE
[invader] Rename native invader tag classes.

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/invader#171]
Since this project aims to be the engine itself, I think it would be better to rename some of the new invader-specific tag classes that intend to replace equivalent HEK tags so it is more clear what they are intended for.

`extended_bitmap` -> `invader_bitmap`
`extended_sound` -> `invader_sound`
`new_font` -> `invader_font`
`new_ui_widget_definition` -> `invader_ui_widget_definition`
`new_unit_hud_interface` -> `invader_unit_hud_interface`
`new_weapon_hud_interface` -> `invader_weapon_hud_interface`

I think tags that have no HEK equivalent, like the planned shader_transparent_glsl don't need the `invader` prefix.

**Comment by Kavawuvi** [comment]
Done as of 2df7c8ae340b39c151c0727abcb2a18f298f25e6
