### ISSUE TITLE
[invader-archive] Add option to copy tags to another location rather than make a compressed archive file.

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/invader#178]
I find myself often using this tool in a way where I immediately extract the generated archive anyway.
Usage would be something like `--copy/-C <dir>`, and invader-archive would then copy the tags into that location, provided the files do not already exist.

A few use-cases for this are either copying out all the tags needed for a single map to another location so they can be edited there, copying the tags for multiple scenarios into one directory so that can then be compressed for archival separately, or merging split "-t" tagsets.

**Comment by Kavawuvi** [comment]
Done as of cffa94964008ee9a3d4ee1c25613341ee8da6289
