### ISSUE TITLE
Stock d40 no longer builds due to script reference error

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/Invader#18]
Attempting to build the gearbox d40.map results in the following error.

```
Cannot resolve script reference explosion_small.
terminate called without an active exception
Aborted (core dumped)```

**Comment by Kavawuvi** [comment]
Fixed in https://github.com/Kavawuvi/Invader/commit/ab86caf16159b6ea7096aafed3ae72f6801afc0b
