### ISSUE TITLE
Include a CRC spoofer tool

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/Invader#19]
While map CRC's can already be changed with the MEK, having a small self-contained dedicated tool that only changes the 4 bytes needed to set the CRC would be advantageous, allowing for much quicker testing and usage of indexed map builds.

**Comment by Kavawuvi** [comment]
Added in https://github.com/Kavawuvi/Invader/commit/95fcc708456ef247d23de3989e1717c711090c2b
