### ISSUE TITLE
Scripts fail to work if compiled into a scenario with sapien

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/Invader#20]
Map scripts will crash the game if they were compiled in with sapien beforehand. They only work if the scenario was ripped directly from a map built with tool.exe.

**Comment by Vaporeon** [comment]
This seems to depend on the map, b40 from the campaign does not crash, but still has bugs.

**Comment by Kavawuvi** [comment]
Fixed in https://github.com/Kavawuvi/Invader/commit/068a58ac691e2abc87ac23eb2ffdd861e5b7bd1f
