### ISSUE TITLE
Jason Jones the weapon tags when building maps for singleplayer.

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/Invader#21]
For reference I think this is stupid and maybe there should be a switch for it, but it's too important to ignore.

The following tags have values changed by tool.exe if the map is for multiplayer.
weapons\pistol\bullet.damage_effect
weapons\pistol\pistol.weapon
weapons\plasma rifle\plasma rifle.weapon

Without this, it would be easy to accidentally build maps with differing weapon stats when using the indexer.

**Comment by Kavawuvi** [comment]
Looks like I need to Jason Jones tags when building for singleplayer too.

The pistol bullet isn't changed when building for multiplayer. It's changed when building for singleplayer, and the Elite Energy Shield modifier is set to 0.8 if this is the case.

Going to look at the other tags.

**Comment by Kavawuvi** [comment]
The pistol weapon's maximum error angle is set to 0.4 when building for singleplayer too. This tag is unchanged when building for multiplayer from the looks of things.

**Comment by Kavawuvi** [comment]
The plasma rifle's error angle is set to 0.25 degrees - 2.5 degrees when built for singleplayer. It is unchanged in multiplayer.

**Comment by Kavawuvi** [comment]
It appears that tool.exe Jason Joneses the tag data when building for singleplayer.

**Comment by Kavawuvi** [comment]
It appears that tool.exe Jason Joneses those tags only when building for singleplayer. A major examples is the globals tag which has a lot of cheats-related stuff stripped in singleplayer.

**Comment by Kavawuvi** [comment]
There may be more stuff to Jason Jones, but the pistol and plasma rifles are at least there. https://github.com/Kavawuvi/Invader/commit/ebc8840526e3f5923c7d753cd4ed54058f4b3e9d

There may be other things being Jason Jonesed such as the non-mp vehicles, other weapons, or other damage effect.
