### ISSUE TITLE
Building with -w can sometimes lead to maps with duplicate tag paths

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/invader#24]
It seems in some cases the generated stub tags will have no name, leading to duplicates in the compiled map.

This happened after trying to clean a hacked map of orphan tags by indexing, de-protecting and rebuilding it twice. ~~I assume that because all the stubs were now literal string list tags, there would be name collisions and invader did not handle this.~~

Rather than directly fix this it may be better to slightly change the way missing tags are handled anyway. Instead of stubbing all of them and saving full paths in the map, you could instead backfill the empty slots with new tags, and in the event the map being built has less tags than the index source, generate empty strings lists for any remaining empty slots with the naming convention `stub/<id>`, or hell just null them if you don't mind doing that. As long as the game and refinery can open it then that is all that should matter, really.

The string lists and paths of stubs don't really do anything for the map other than waste tag space. That information is better off as a build time log rather than something stored in the map.

**Comment by Vaporeon** [comment]
This is my fault as I deleted known pointless lines from an index file without changing the tag count at the top. It seems invader will insert empty stub tags with no name until the count is reached.

**Comment by Kavawuvi** [comment]
For the most part the issue is resolved as missing tags are now called MISSINGNO. and cannot be extracted due to using a tag class of 0xFFFFFFFF.

However, the number of tags in the index isn't necessary anymore, so to completely fix this, this number will have to be removed.

**Comment by Kavawuvi** [comment]
Finally got around to removing the number https://github.com/Kavawuvi/invader/commit/ea6c0bf59b1cc4793fa7dd39315b4c058fdabfee
