### ISSUE TITLE
Tool to extract tags from maps

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/invader#35]
Although tag extraction already exists, I think it would be good for invader to be able to extract tags form maps as part of the toolset it provides.

This extraction tool should be that only, A tool that simply extracts maps as they are without second guessing them due to the abundance of corrupt maps. Corruption repair AKA deprotection should be left to another program.

**Comment by Kavawuvi** [comment]
Great idea! I'd like to do https://github.com/Kavawuvi/Invader/issues/36 first. Having it in a parseable format means writing a lot less code to do extraction since I don't have to hardcode every single data field. This reduces user error and makes bugs easier to fix.

**Comment by Kavawuvi** [comment]
Done in https://github.com/Kavawuvi/invader/releases/tag/0.19.0
