### ISSUE TITLE
Tag definitions should be stored in a parseable format

### ISSUE THREAD

**Issue by Kavawuvi** [Kavawuvi/invader#36]
Invader currently uses header files for tag definitions. While this is very fast as all offsets and the ways these values are read are determined at compile-time, it also makes it difficult to do things like iterate through tag values.

Ideally these definitions should be done in a parseable format such as .json or .xml, and then they can be parsed. We can then generate header files from these definitions when Invader is built so performance won't be impacted.

**Comment by Vaporeon** [comment]
Completed as of a0242f9d680d12bd2c387393c47578697110b09d
