### ISSUE TITLE
Add a tool for creating font tags

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/Invader#38]
The released tool.exe font tag creation feature seems to not work as well as whatever version bungie used for the xbox font tags. An open replacement is really needed. It would also be nice to create halo fonts without wine or windows too.

**Comment by Kavawuvi** [comment]
It appears bitmaps are just straight-up A8 monochrome data. All one would need is to be able to rasterize every character in a font into a font tag.

**Comment by Kavawuvi** [comment]
Done in https://github.com/Kavawuvi/Invader/commit/5fff98ada2e4fac63f1cd6e5563d7449e8fdc78a
