### ISSUE TITLE
invader-resource should have an option to include an existing resource map data

### ISSUE THREAD

**Issue by Kavawuvi** [Kavawuvi/Invader#42]
This will allow the resource map to work with cache files that use external offsets instead of indices (i.e. aXX, bXX, cXX, dXX, and ui maps built with tool.exe) without corrupted sounds and bitmaps appearing.

This will also allow for people on non-English copies of the game to play English maps without corrupted sounds and bitmaps appearing while having maps that properly use indices use the correct language assets.

Obviously this should only apply to sounds or bitmaps, not loc which can only be referenced with indices.

**Comment by Vaporeon** [comment]
After learning about how tool.exe exactly handled this, I have come to think this is unnecessary.
It might have made sense if it was true that all campaign maps were depending on offsets, but as in reality is is only maps named a10, a30, a50, b30, b40, c10, c20, c40, d20, d40 and ui.

So first off, unlike what was first thought, any custom single player map NOT named as above will be immune to this issue. So in reality, for single player only the original broken Campaign ports, CMT SPV1, the unfinished SPV2 the current Refined Campaign builds and the odd stand in mod map will be effected.

I consider this a small deal, the first reason being these maps can all be rebuilt with current tools, and secondly in reality there are only a handful of them. most importantly these maps are not mutually exclusive, meaning you can only have one set of these installed at once. This means you are already having to copy the maps in an and out manually to play them so changing them for rebuilds if using a different resource map set should not be that much extra work. I don't mind making the rebuilds for the few maps out there that fall into this category.

Next comes UI maps, Yeah, every custom UI and the stock UI will break if you make custom resources, however this too I think is worth rebuilding for. This would not be too much effort as someone already went to the trouble of archiving every custom UI, and having checked these, most are just re-skins of the stock UI. Rebuilding these will be of great value not just to make them work with localizations and custom resources, but also to make them more feature complete with each other, like versions with campaign support and HEK+ bugs can be trivially fixed thanks to invader's stacked tag directories support.

People releasing custom resources should at least make sure it comes with a indexed stock UI so the game can run.

I will go through the UI archive myself and fix everything up, then users of new resources can just use these, again if they are manually installing resources then installing a new UI to go with it is not much more effort.

Finally there are multilayer maps that may use external pointers.
I have gone through every Custom Edition MP map in the HAC2 repo, two maps were found with external pointers and in both cases these were invalid. This is a non issue.

**Comment by Kavawuvi** [comment]
After some careful consideration, I've determined that this may not be a good idea to support and implement. There are a few reasons why:
- Doing this would increase the size of the resource maps by about 31%, increasing the total size from ~0.5 GiB to ~0.66 GiB. Half a gigabyte may already be a hard ask for some people, especially since a few modders are, for some reason, very pedantic about the file sizes. This would push it even further.
- The only reason to do this would be to support maps that were not compiled using invader-build or a patched tool.exe.
- Such maps could be extracted and rebuilt using invader-build or a patched tool.exe to use the new resource maps.
- Also, considering it only affects maps based on file name, this issue really only addresses a very small subset of maps.
- This is not a fix. It is a workaround, and it doesn't take very long to fix the actual problem. It just adds on cruft to a game that arguably has enough cruft already.
