### ISSUE TITLE
invader-build could have an argument to always use indexed tags when building maps

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/Invader#43]
Essentially the opposite to -n. Tags would be indexed under the only condition of matching paths with the resource maps.

The use-case is if you are editing some tags that contain different stock tags that what is currently in the resource map, and you would rather use the resource tags regardless.

I know you could just update the tags, but this could become very tedious especially if dealing with multiple tag directories and/or ripped maps you are changing slightly.

**Comment by Vaporeon** [comment]
I'd like to add that the HEK comes with English tags, but you may be using another localization. This feature would be useful here otherwise invader would internalize the base HEK tags into maps.

**Comment by Kavawuvi** [comment]
Done in https://github.com/Kavawuvi/Invader/commit/579a8a5503bef055952e057a9a7d071a99cd796a
