### ISSUE TITLE
Create a tool to archive the original tags needed to build a map.

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/Invader#45]
A tool could be created that takes the same input as invader-build, but rather then building a cache file, it adds every tag that would have been used in that process to a 7z archive.

This tool could also support multiple tag paths like the other tools, so for example if you ran `invader-archive levels/whatever/map -t tags1 -t tags2`, you would get an archive containing the tags that would have been used from each directory.

This feature would be great for storing tags for archiving or giving to someone else to use.

While you could just extract the map again, those tags have extra data stripped like the original source scripts and uncompressed pixel data in bitmaps, so having a tool to archive those without manually picking through tag directories that could contain thousands of tags each would be very helpful.

**Comment by Kavawuvi** [comment]
Done as of https://github.com/Kavawuvi/Invader/commit/cca55002ff2aca866cdc040cf737c88b6febfd1a
