### ISSUE TITLE
[invader-build] Add a way to safely ensure maps work with the original resource maps

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/Invader#48]
The option could possibly be `-s --safe-indexing`

It would take the tag count from the original bitmaps/sounds/loc and then right before indexing check if the id goes above that value when that option is used, if so the tag gets built into the map.

Lets say you are using full custom resources but you want to build a map that works with the original stock resource maps. Well, you could use this new option and it would never index a tag if the index id would be higher than what is in the original resource maps ensuring will work with them.

**Comment by Kavawuvi** [comment]
Done in https://github.com/Kavawuvi/Invader/commit/24eaff0c3488a1fd680e4f8314864d3b2937eceb and it is not optional
