### ISSUE TITLE
Ensure the tag paths of created tags are lowercase

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/Invader#49]
Currently invader-bitmap and invader-font will output whatever the source name is, however I think all tags should be converted to lowercase on creation to ease the pain on case-sensitive filesystems as cache files themselves are not case sensitive.

One thing bungie/gearbox got right is all stock tags are lowercase, and current tag extraction tools will change any custom tags to lowercase too if they are not already. Invader could do it's part by ensuring tags are always lowercase when possible.

**Comment by Vaporeon** [comment]
Interestingly when you open tags with guerilla it will always display the tag name as lower-case in the menus.

**Comment by Kavawuvi** [comment]
Perhaps invader-build should also error if you try to compile any tags that have uppercase characters in their paths.

**Comment by Kavawuvi** [comment]
Added in https://github.com/Kavawuvi/Invader/commit/1f262920aac00f018fae95e7534fc1bbea1b21dd and https://github.com/Kavawuvi/Invader/commit/b7ff2f81d9127a70ca0a3eae41fdf136800dd621
