### ISSUE TITLE
Add a way to optimise away stubbed tags.

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/Invader#50]
I thought I'd open an issue for this to post ideas.

A compatible map is likely to use different bitmap and shader tags as it is one of the main reasons to use this feature. Thus lots of stubs for network-unimportant tags will occur.

Currently tags are stubbed by generating string lists with the class and full path.
This is rather messy in my personal opinion and not so good if someone extracts the map and has all this cruft around.

A possible way to remove stubs is to fill the gaps with non-network object tags that exist after the last network object with the highest index id. In the event a map runs out if these tags due to containing less tags than than the original map, a string list stub could be created with the name `stub/<indexid>` as a fallback. That is very unlikely though as you would have to go through swaths of ui tags first to get there.

Another option is to compile in all the missing tags to keep the map complete should someone want to do this. I know I complained about orphan tags before but then I realised you could just reference them in the scenario tag references array. I'd generate a tag collection of the missing tags and use that since this is used for scripts too and we might not want to fill it up with too many tags.

You could possibly allow the user to choose between fat builds with all tags and optimised builds with a command line switch. Fat builds are rather wasteful of tag data and possibly raw data though but has a use if someone wants to make a change without removing anything.

Technically these options could be done by building the map internally twice when using -w, the first used to know what tags are is missing if any or getting a list of tags that can be used to optimize away stubs. Then the second build would then be the final cache file.

**Comment by Kavawuvi** [comment]
I've made it a bit less memed by just using the same tag path, an invalid tag class, and no tag data for each tag, thus the tags won't be extracted by a tool such as Refinery, nor will it affect the game in any way. This should fix most problems.

The extra (32*stubcount + 11) bytes isn't going to be significant, either, unless you have hundreds of stubbed tags. Ideally you shouldn't have any stubs or at least very many of them, as stubbing out tags is more-or-less a form of error handling.

I don't want to go into this any further right now, as it will never be ideal as long as you have stubs.

**Comment by Vaporeon** [comment]
I find the latest change is adequate for improving the usage of maps containing stubs.

I have also have come to disagree with the idea of compiling in all the missing tags as the indexer is not intended to be used as a means of referencing tags into a map.
