### ISSUE TITLE
Remove "or later" GPL clause from all source files

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/Invader#53]
Richard Stallman has stepped down as the leader and board member of the Free software Foundation due to some political bullcrap that we need not go into here.

This brings up an interesting point. The FSF has full power to write the license file for many software projects that include that clause. RMS dedicated his life to free software and had very extreme views on supporting it, making him an extremely rare person you could undoubtedly trust with such power. However, with FSF leadership up in the air should that organisation be trusted with such power still? personally I don't think it should and having a legally binding automatic assumption that a future GPLv4 would be a good license is unwise.

**Comment by Kavawuvi** [comment]
I prefer to not go into a discussion about stuff like this, but I do agree that having an "or later" part adds uncertainty that I may not want in an open source project.
