### ISSUE TITLE
3D textures' depth should be halved when generating mipmaps as well

### ISSUE THREAD

**Issue by Kavawuvi** [Kavawuvi/invader#56]
3D textures are textures that have a width, height, and depth. When calculating mipmaps, Halo halves all three of these. Currently Invader only halves the width and height.

The question is: how are 3D mipmaps generated? Does take every other layer, or does it blend every couple of layers? Testing will need to be done here.

**Comment by Vaporeon** [comment]
It might be a good idea to disable the creation or modification of 3d-texture tags until this is fixed.

**Comment by Kavawuvi** [comment]
From experimentation, it looks like it does a blending of the two layers.

**Comment by Kavawuvi** [comment]
Done in https://github.com/Kavawuvi/invader/commit/b883b78ad4c6b74a76847bcade9dcc9487629b73
