### ISSUE TITLE
Create a tool to display information on existing cache files

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/invader#59]
It would be quite useful to have a command line tool that loads a cache file and displays some basic information about it.

Some of the information could be:

- the map name as set in the header
- the engine the map is built for
- the size of the tag data
- the size of the map, also checked by parsing the tag data and checking if the real file size matches.
- the CRC of the map and show if it matches the header (basically do what invader-crc does, thus depreciating it).
- a list of tags in the map, ordered by index (replacing the indexer?)

**Comment by Kavawuvi** [comment]
I've added invader-info.

That said, I'm not sure I'd want to replace the indexer with this, as it is assuming that everyone's shell can pipe standard output to a file.

**Comment by Kavawuvi** [comment]
I've added invader-info as of https://github.com/Kavawuvi/invader/commit/66d8557ea9eebbf39c1ac56b258636f57eb01fc7

That said, I'm still not sure if I'd want to replace the indexer with this.

**Comment by Kavawuvi** [comment]
Add tag listing to https://github.com/Kavawuvi/invader/commit/73c3da4119c4e687e63f4034f9c9010e9a6900d5
