### ISSUE TITLE
[New feature] Tool to refactor tag references

### ISSUE THREAD

**Issue by Kavawuvi** [Kavawuvi/invader#61]
Renaming tags requires going through every tag that references it and changing the dependency. Refinery provides the option to rename tag paths in existing maps and then extracting. However, while extracted tags are functionally equivalent to the original HEK tags (if extracted correctly), data that isn't included in maps, like color plate data, is permanently lost.

What this tool could do is change tag references en masse. What you do is input the original tag path and point it to the new tag path (either using relative paths or filesystem paths with `-P`). It then goes through all of the tags directories given to it and re-references any tags that reference the tag to this new path.

Note that this should NOT change script string data as it only affects the script, not the source .hsc file, thus it's out of the scope of this tool.

Also note that this does NOT rename or move the file. In fact, whether or not the original tag still exists with its original path is not important. All that matters is that the new tag exists when the map is built, and how that is done is up to the modder.

Also, this will require https://github.com/Kavawuvi/invader/issues/36 to be completed.

**Comment by Vaporeon** [comment]
This was added in 8ff0451289a80602ac1eaedada8e0e78fad689a8
