### ISSUE TITLE
Add "make install" function to build script

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/invader#63]
Since invader is getting to be a large project, the cmake generated makefile should have an install function that installs the required files and headers to the correct locations. This will ease packaging as packages can simply run the install command rather than explicitly install everything manually.

**Comment by Kavawuvi** [comment]
Added as of https://github.com/Kavawuvi/invader/commit/e8688d876862bfcc3c741a9f4ed0838c65e4c2d3
