### ISSUE TITLE
[invader-build] Inconsistent values in rebuilt light tags

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/invader#73]
After extracting a map with invader-extract, and rebuilding it, some hidden values seem to be inconsistent when comparing the two in Eschaton. Seems to happen on any map.

**Comment by Kavawuvi** [comment]
Halo stores pi as 3.14159274101257, and invader-build uses the C standard's sin function, which turns that value into -8.74227769 x 10<sup>-8</sup>, where tool.exe calculates it to 0. This discrepancy is less than 0.0000001 off, this appears to be more a precision difference.

Unfortunately, this can result in some bytes being different even when it's too insignificant to affect anything, but it's not something I can or will try to fix.
