### ISSUE TITLE
[invader-extract] Tags extracted from combustion maps can cause earrape

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/invader#75]
In order to reproduce this, you need tags that have been touched by the Combustion Retail>CE cache file conversion tool.

To reproduce, first convert stock retail bloodgulch to CE format with Combustion, allowing it to optimise against the CE resource maps.
Second, extract that map with invader-extract. Some tags will not extract, just extract them from the original retail bloodgulch map so it builds again. The issue is in the sound tags that do extract.
Third, rebuild the map with invader-build (git master). sounds will be glitched.
~~If you build these same tags with tool.exe the map works fine.~~

**Comment by Vaporeon** [comment]
As I should have known, it's not that tool can handle the tags, it's that tool's crappy resource check means the broken tags get indexed away.

**Comment by Vaporeon** [comment]
Since the tag data in the map is likely corrupt but happens to work fine in game, this map is really something that should be run through a de-corruption tool.

invader-extract is a bullshit in - bullshit out tool, and it should stay that way, however it is too easy to extract bullshit without even realising it. There needs to be a way to inform the user they did not get what they were expecting, so perhaps invader-extract should possibly do error checking on all tags it extracts.

I also think it would be wise to have it not extract dirty maps by default, but this is not 100% foolproof as it is technically possible to restore it to a "clean" state while leaving the bullshit intact.

**Comment by Kavawuvi** [comment]
Fixed in 1c44335e1462be86de9abb0c6027a114fb87c75c
