### ISSUE TITLE
[invader-build] Missing default values in decal tags

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/invader#77]
Currently some values in decals are not defaulted causing newly created tags to not work.

Radius should be defaulted to 0.125
Intensity should be defaulted to 1
Color lower and upper bounds should be defaulted to 1 in each channel.

**Comment by Kavawuvi** [comment]
Done in https://github.com/Kavawuvi/invader/commit/1ac68e86232d41422c632bdbb8023d23a4a49cae
