### ISSUE TITLE
[New feature] Check tags for errors after building

### ISSUE THREAD

**Issue by Kavawuvi** [Kavawuvi/invader#8]
Invader should check tags for errors after building the map. Some tags may be completely valid as tags but may have an invalid index which could result in a crash, either due to user error, data corruption, or a tool breaking something. It is worth noting that tool.exe does some amount of verification upon using build-cache-file.

This feature should be optional, as it may not be necessary every single time a map is built. Also, this feature should be usable on existing cache files, thus it may make sense to have this be its own program rather than be strictly part of invader-build (invader-build could still call it as a function).

This feature was suggested by MosesofEgypt.

**Comment by Vaporeon** [comment]
Maybe such a standalone tool should be able to check both maps and loose HEK tags as well. You could have it take either a map, a tags directory or a single tag as input, then print and found issues with the tag/s or map, e.g. invalid references.

**Comment by Kavawuvi** [comment]
invader-build is better off checking for errors while building. The checks do not take that much time, and it is way easier to check for issues as the map is being built.
