### ISSUE TITLE
Missing decals on Blood Gulch bases

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/Invader#9]
The decals on the outside of both Blood Gulch bases do not render when the map is built with invader.

**Comment by Kavawuvi** [comment]
Fixed in 7b66376be6f462591f6722db1dd3be6403b9674e

**Comment by Kavawuvi** [comment]
Apparently this is not fixed in the newer tagset.

**Comment by Kavawuvi** [comment]
It's now fixed in f7f26453e5259d42048b267d40efedb9aced553f
