### ISSUE TITLE
[invader-build] Jason Jones some damage effect stun values and weapon tags when building stock Halo maps to match values used on the target engine.

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/invader#94]
Gearbox decided to change some tag data to remove stun from the banshee and ghost for the release of Halo Custom Edition.

Since these values effect the netcode syncing it might be best for us to just set them the values used on the given engine target when building an original multiplayer map. This would ONLY apply when building stock maps. This way tags extracted from any released stock map can be used to safely rebuild the map for any supported version of the game without prior knowledge of these slight changes made.

These three stun values are set to `0` on Custom Edition, while they are the below values for retail and demo.

```
vehicles/banshee/banshee bolt.damage_effect
vehicles/ghost/ghost bolt.damage_effect
stun 1
maximum stun 1
stun time 0.15

```
The rocket warthog gun weapon tag was also changed.
```
Retail/Demo:
vehicles/rwarthog/rwarthog_gun.weapon
(aim assist)
autoaim angle 1
autoaim range 25
magnetism angle 12
magnetism range 25
deviation angle 1
```
```
Custom Edition:
vehicles/rwarthog/rwarthog_gun.weapon
(aim assist)
autoaim angle 6
autoaim range 25
magnetism angle 12
magnetism range 25
deviation angle 12
```

**Comment by Kavawuvi** [comment]
Done
