### ISSUE TITLE
[invader-build] throw a pedantic warning whenever something was "Jason Jonesed" (purple text)

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/invader#95]
The build output text should log whenever tag data values have been overridden for some reason so the user knows what is going on and why this might have happened. This should also apply for extraction.

**Comment by Kavawuvi** [comment]
This was done a while ago for invader-build. invader-extract doesn't have any warning system yet, so I'm leaving this issue open.

**Comment by Kavawuvi** [comment]
Done as of https://github.com/Kavawuvi/invader/commit/cbfe52e9fefa281dcb453af93f8d0c4cce14f176
