### ISSUE TITLE
[invader-build] Use default tag index lists when building stock multiplayer maps.

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/invader#96]
Since we have all these checks for stock stuff anyway we might as well do this too as a convenience.
Custom Edition CRC32's can be defaulted too, for stock scenarios.

This way extracting and rebuilding stock maps with invader can produce maps that work online by default.

Here is the indexer output for all official PC cache files across all releases. [cache_indices.zip](https://github.com/Kavawuvi/invader/files/4049841/cache_indices.zip)

**Comment by Kavawuvi** [comment]
Done
