### ISSUE TITLE
[invader-build] Change the default build target to retail

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/invader#97]
Since invader is intended to be a modding toolkit for "Halo: Combat Evolved on the PC" then perhaps we should default to the original retail release when building maps.

This is the most complete version of the game whereas both Custom Edition and the demo are forks created with a specific feature in mind; one of these releases actually fails to properly serve its intended purpose.

However if we do this we need to better handle how these maps are built when it comes to resource maps, as many people may want to build for Custom Edition and they likely will not expect retail maps compiled against Custom Edition resource maps as what would be produced by default. It would be nice if there were some way of identifying what engine the resource maps are for first before using them.

**Comment by Kavawuvi** [comment]
It may be better to just require the user to select the game every time a map is built, as the original, unmodified release does *not* support custom maps.

**Comment by Vaporeon** [comment]
Yeah this makes the most sense. Assuming engines and current resource maps is very unsafe and worth the small amount of extra text you have to type in order to run invader-build.
